---
- name: mongodb | Create the yum repo for mongodb
  copy: src=yum-mongodb.repo dest=/etc/yum.repos.d/mongodb.repo

- name: mongodb | Install mongodb
  yum: name=mongodb-org state=installed
  notify: mongodb | restart mongod
  