---
- name: nginx | restart nginx
  service: name=nginx state=restarted

- name: iptables | save iptables
  command: /sbin/service iptables save

- name: iptables | restart iptables
  service: name=iptables state=restarted

- name: playchaser | add playchaser-app to init
  service: name=playchaser-app enabled=yes

- name: playchaser | start playchaser
  command: service playchaser-app restart
